sudo: required

services:
  - docker

language: node_js

env:
  - MONGODB_SERVICE_HOST=localhost
  - MONGODB_SERVICE_PORT=27017

before_install:
  - docker pull mongo
  - docker pull node
  - docker run -d -p 27017:27017 --name mongodb mongo

install:
  - npm install

script:
  - npm test

after_success:
  - docker build -t gregvers/hitcount .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push gregvers/hitcount;
    fi
