sudo: required

services:
  - docker

language: node_js

before_install:
  - docker pull mongo
  - docker run -d -p 27017:27017 --name mongodb mongo
  - docker pull node
  - docker build -t gregvers/hitcount .
  - docker run -d -p 3000:3000 --link mongodb:mongo gregvers/hitcount
  - docker ps -a

script: npm test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push gregvers/hitcount;
    fi
